before_install:
- chmod +x mvnw
jdk:
- oraclejdk8
install:
- "./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V"
language: java
deploy:
  provider: gae
  keyfile: unitalq-backend-c648f9bbacb4.json
  app: unitalq-backend
  on:
    repo: p4ch1n0/uniLifeJava
    branch: development
  skip_cleanup: true
before_script:
script:
  - mv src/main/resources/application.properties src/main/resources/application.properties.h2
  - mv src/main/resources/application.properties.post src/main/resources/application.properties