before_install:
  - chmod +x mvnw
jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
language:
  java



