before_install:
- openssl aes-256-cbc -K $encrypted_74f4b4028820_key -iv $encrypted_74f4b4028820_iv
  -in unitalq-backend-fbdc27bb53db.json.enc -out unitalq-backend-fbdc27bb53db.json
  -d
- chmod +x mvnw
jdk:
- oraclejdk8
install:
- "./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V"
language: java
deploy:
  provider: gae
  keyfile: unitalq-backend-fbdc27bb53db.json
  app: unitalq-backend
  on:
    repo: p4ch1n0/uniLifeJava
    branch: development
  skip_cleanup: true
before_script: 
script:
- mv src/main/resources/application.properties src/main/resources/application.properties.h2
- mv src/main/resources/application.properties.post src/main/resources/application.properties
