before_install:
- chmod +x mvnw
jdk:
- oraclejdk8
install:
- "./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V"
language: java
deploy:
  provider: heroku
  api_key:
    secure: NsbuNaW4rmFWKWRJCxJ/R9vcguKJ2J7f2xGoWIVVX52OUykUVchn6/Si0zKkkxYKNAb/HZ7LS83qQqiNX6CRA4nVwDEMadOQ9md7rp9hDdYyGSXO5ZasHWNM45maDxiNIHv3yDaHHBX2yQ8TUu03QhJoAwPuupRI+KDlJubkYICO0jXvJpRH07zBz0puLKRk+Qh5kEbpfSwhelb0GsPo9CF0yYt0gT9uIOoqeIiYp/9c8qq5dl22U8eQgCR5w9TUG1bn0h0uKi7zt7PMsb8tSzK4jbbzea0q1PlXpy7HfaNPXF6io0zWSeG4fy22/gxjM5J58w52aJwMLDvmKcA9J8K+7s+DAYKtnZJjRLVQbskzOzwrP+M5HGC4qHo4AsoQ2+MfKTtlg76cZvMVcCMOCxyux8QLdT1zjchORpT9oZZ8OjT+3hCiZGGGiTAclpm6E3zY5U0ILweCUpj8UQ136iPUhyKN/gHjzz9xsWe1DQkjxz4ct7kLYCKd6wOIGN1bewqkS7VvjnKDOZbGM+lTQmWsJLfQncEw0OB74q7zivdhzEySd/JPuli1mlwumLKexP0SZRO16O1x3OydF4egIPaEexdKy4VxG+HYpRSBtq40afs+jmzymdiEjlHd5uA8SpnASjSYmnikwU5ocRT5p6ZXM1DXoOxyDl95sp68glA=
  app: uniLifeJava
  on:
    repo: p4ch1n0/uniLifeJava
    branch: development
