version: 0.2
phases:
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - mvn install -DskipTests=true
artifacts:
  files:
    - target/uniReddit-0.0.1-SNAPSHOT.jar
  discard-paths: yes