version: 0.2
phases:
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - mv src/main/resources/application.properties src/main/resources/application.properties.h2
      - mv src/main/resources/application.properties.post src/main/resources/application.properties
      - mvn install -DskipTests=true
artifacts:
  files:
    - target/uniReddit-0.0.1-SNAPSHOT.jar
  discard-paths: yes