version: 0.2
phases:
  pre_build:
    commands:
      - mv src/main/resources/application.properties.h2 src/main/resources/application.properties.h2.h2
      - mv src/main/resources/application.properties.h2.post src/main/resources/application.properties.h2
      - mvn test
  build:
    commands:
      - mvn install -DskipTests=true
artifacts:
  files:
    - target/uniReddit-0.0.1-SNAPSHOT.jar
  discard-paths: yes